#!/bin/sh
#
### BEGIN INIT INFO
# Provides:          pinba2zmq
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Daemon for collection pinba stats and sending it to ZeroMQ socket
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/local/bin/pinba2zmq
NAME=pinba2zmq
DESC="Daemon for collection pinba stats"
DAEMON_OPTS="--log /var/log/$NAME.log"
PIDFILE="/var/run/$NAME.pid"

test -f $DAEMON || exit 0
set -e

# set memory limits (kbytes)
ulimit -m 500000
ulimit -v 500000

#
# Function that starts the daemon/service
#
do_start()
{
	[ -e $PIDFILE ] && return 1
	start-stop-daemon --start --quiet --background --make-pidfile --pidfile $PIDFILE \
		--exec $DAEMON -- $DAEMON_OPTS || return 2
}

#
# Function that stops the daemon/service
#
do_stop()
{
	[ -e $PIDFILE ] || return 1

	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
	RETVAL="$?"
	[ "$RETVAL" = 2 ] && return 2

	start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
	[ "$?" = 2 ] && return 2

	rm -f $PIDFILE
	return "$RETVAL"
}

case "$1" in
  start)
  	echo -n "Starting $NAME with $DAEMON_OPTS: "
	do_start
	echo "OK"
	;;
  stop)
	echo -n "Stopping $NAME: "
	do_stop
	echo "OK"
	;;
  restart)
	echo -n "Restarting $NAME: "
	do_stop
	sleep 1
	do_start
	echo "$NAME."
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart}" >&2
	exit 1
	;;
esac

exit 0